export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST';
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS';
export const ADDRESS_LIST_FAIL = 'ADDRESS_LIST_FAIL';

export const ADDRES_ADD_REQUEST = 'ADDRES_ADD_REQUEST';
export const ADDRES_ADD_SUCCESS = 'ADDRES_ADD_SUCCESS';
export const ADDRES_ADD_FAIL = 'ADDRES_ADD_FAIL';
export const ADDRES_ADD_RESET = 'ADDRES_ADD_RESET';


export const ADDRESS_REMOVE_REQUEST = 'ADDRESS_REMOVE_REQUEST';
export const ADDRESS_REMOVE_SUCCESS = 'ADDRESS_REMOVE_SUCCESS';
export const ADDRESS_REMOVE_FAIL = 'ADDRESS_REMOVE_FAIL';