export const HOME_PAGE_CATEGORY_LIST_REQUEST = 'HOME_PAGE_CATEGORY_LIST_REQUEST';
export const HOME_PAGE_CATEGORY_LIST_SUCCESS = 'HOME_PAGE_CATEGORY_LIST_SUCCESS'
export const HOME_PAGE_CATEGORY_LIST_FAIL = 'HOME_PAGE_CATEGORY_LIST_FAIL'


export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const WISHLIST_REQUEST = 'WISHLIST_REQUEST';
export const WISHlIST_SUCCESS = 'WISHlIST_SUCCESS';
export const WISHLIST_FAIL = 'WISHLIST_FAIL';