export const PRODUCT_LIST_BY_CATEGORY_REQUEST =
  'PRODUCT_LIST_BY_CATEGORY_REQUEST';
export const PRODUCT_LIST_BY_CATEGORY_SUCCESS =
  'PRODUCT_LIST_BY_CATEGORY_SUCCESS';
export const PRODUCT_LIST_BY_CATEGORY_FAIL = 'PRODUCT_LIST_BY_CATEGORY_FAIL';


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_LIST_BY_CATEGORY_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';