export const PRODUCT_LIST_BY_CATEGORY_REQUEST =
  'PRODUCT_LIST_BY_CATEGORY_REQUEST';
export const PRODUCT_LIST_BY_CATEGORY_SUCCESS =
  'PRODUCT_LIST_BY_CATEGORY_SUCCESS';
export const PRODUCT_LIST_BY_CATEGORY_FAIL = 'PRODUCT_LIST_BY_CATEGORY_FAIL';


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_LIST_BY_CATEGORY_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';
;