export const PRODUCT_LIST_BY_CATEGORY_REQUEST =
  'PRODUCT_LIST_BY_CATEGORY_REQUEST';
export const PRODUCT_LIST_BY_CATEGORY_SUCCESS =
  'PRODUCT_LIST_BY_CATEGORY_SUCCESS';
export const PRODUCT_LIST_BY_CATEGORY_FAIL = 'PRODUCT_LIST_BY_CATEGORY_FAIL';

export const PRODUCT_LIST_BY_SUB_CATEGORY_REQUEST =
  'PRODUCT_LIST_BY_SUB_CATEGORY_REQUEST';
export const PRODUCT_LIST_BY_SUB_CATEGORY_SUCCESS =
  'PRODUCT_LIST_BY_SUB_CATEGORY_SUCCESS';
export const PRODUCT_LIST_BY_SUB_CATEGORY_FAIL = 'PRODUCT_LIST_BY_SUB_CATEGORY_FAIL';


export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_LIST_BY_CATEGORY_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL';
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';


export const PRODUCT_PRIORITY_HOME_PAGE_LIST_REQUEST =
  'PRODUCT_PRIORITY_HOME_PAGE_LIST_REQUEST';
export const PRODUCT_PRIORITY_HOME_PAGE_LIST_SUCCESS =
  'PRODUCT_PRIORITY_HOME_PAGE_LIST_SUCCESS';
export const PRODUCT_PRIORITY_HOME_PAGE_LIST_FAIL =
  'PRODUCT_PRIORITY_HOME_PAGE_LIST_FAIL';
 

  export const NEAREST_PRODUCT_REQUEST = 'NEAREST_PRODUCT_REQUEST';
  export const NEAREST_PRODUCT_SUCCESS = 'NEAREST_PRODUCT_SUCCESS';
  export const NEAREST_PRODUCT_FAIL = 'NEAREST_PRODUCT_FAIL';
 
 